# Generated by Django 4.0 on 2022-01-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.CharField(max_length=15, unique=True)),
                ('id_type', models.CharField(choices=[('CC', 'Cedula de ciudadanía'), ('NIT', 'Identificación Tributaria')], default='CC', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factapp.typeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factapp.client')),
                ('invoice_issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factapp.product')),
            ],
        ),
    ]
