# Generated by Django 4.0 on 2022-01-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeproduct',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
